### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by hanulhanul** [hanulhanul/BEB-06-FIRST-08#1]
### Bare Minimum (필수)
* 헤더 생성 
- [ ] 웹페이지 로고를 누르면 메인 페이지로 돌아감
- [ ] 검색창 및 버튼
- [ ] 지갑 연결 버튼
  - [ ] 지갑 연결을 했을 때, 지갑 연결이 되어 있는 상태를 표시할 수 있는 로고
  - [ ] 지갑 연결을 하지 않았을 때, 지갑 연결되어 있지 않는 상태를 표시할 수 있는 로고
 - [ ] 마켓, NFT민팅, 마이페이지 내비게이션
* 메인 페이지 (랜딩 페이지)
   - [ ]  NFT 리스트
     - [ ] 10페이지 단위씩 볼 수 있도록 페이지네이션으로 개발
      - [ ] 게시글 제목에 커서를 대면 커서가 누르는 모양으로 바뀌어야 함
      - [ ] 서버에서 NFT 리스트 데이터를 받아와야 함

### Recommended (권장)
* NFT 민팅 페이지
   - [ ] 리액트에서 제공하는 기본 폼으로 NFT 민팅 페이지를 개발
   - [ ] 이미지, 이름, 상세내용 칸 있어야 함
   - [ ] 민팅 버튼을 누르면, 지갑 서명 통해 트랜잭션 수행해야 함
* 테마별 NFT 리스트 페이지
  - [ ] 탭 기능 사용하여 테마별 NFT 리스트 조회 가능해야 함
  - [ ] NFT 이미지와 작가 이름 존재해야 함
  - [ ] 목록 버튼을 누르면 게시글 리스트의 클릭했던 목록으로 돌아감

### Advanced (도전해볼만 합니다)
* NFT 상세 페이지
 - [ ] 이미지를 포함한 NFT 상세 정보를 보여줄 수 있어야 함
 - [ ] 거래되는 가격을 보여줄 수 있어야함
 - [ ] 구입버튼을 누르면 지갑을 통해 트랜잭션을 수행할 수 있어야 함
* 마이 페이지
- [ ] 프로필, 보유한 NFT, 발행한 NFT 를 볼 수 있어야 함
- [ ] 지갑 연결을 해제할 수 있어야함
- [ ] Mouse :: hover 하면, 멈춥니다. t

### Nightmare (신중히 결정하세요)
